config/routes.rb
Wuthlesscoin::Application.routes.draw do
  devise_for :admins

  resources :coins

  get "mash", :to => "home#mash"
  get "mashes", :to => "coins#mash_list"
  get "ips", :to => "coins#ip_list"
  get "ips/:rpi_id/:mash", :to => "home#ips"

  root :to => "home#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/coin.rb
class Coin < ActiveRecord::Base
  attr_accessible :name, :num_coins
end

app/models/mash.rb
class Mash < ActiveRecord::Base
  attr_accessible :val
end

app/models/rpi_ip.rb
class RpiIp < ActiveRecord::Base
  attr_accessible :ip, :ping, :rpi_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_filter :authenticate_admin!
  
  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coins }
    end
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
    @coin = Coin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coin }
    end
  end

  # GET /coins/new
  # GET /coins/new.json
  def new
    @coin = Coin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coin }
    end
  end

  # GET /coins/1/edit
  def edit
    @coin = Coin.find(params[:id])
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(params[:coin])

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render json: @coin, status: :created, location: @coin }
      else
        format.html { render action: "new" }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coins/1
  # PUT /coins/1.json
  def update
    @coin = Coin.find(params[:id])

    respond_to do |format|
      if @coin.update_attributes(params[:coin])
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin = Coin.find(params[:id])
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url }
      format.json { head :no_content }
    end
  end

  def ip_list
    db_ips = RpiIp.all

    render json: {"ips" => db_ips}
  end

  def mash_list
    db_mashes = Mash.all

    render json: {"mashes" => db_mashes}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @coins = Coin.order("num_coins DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coins }
    end
  end

  def mash
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    string = (0...50).map { o[rand(o.length)] }.join

    Mash.create!({:val => string})

    render json: {"result" => string}
  end

  def ips
    if params[:mash].nil?
      render json: {"result" => "error"}
      return
    end
    db_mash = Mash.where(:val => params[:mash]).first
    if db_mash.nil?
      render json: {"result" => "error"}
      return
    end

    db_rpi_ip = RpiIp.where(:rpi_id => params[:rpi_id]).first
    db_rpi_ip = RpiIp.create!({:rpi_id => params[:rpi_id]}) if db_rpi_ip.nil?

    db_rpi_ip.ip = request.remote_ip
    db_rpi_ip.ping = DateTime.now
    db_rpi_ip.save!

    db_mash.destroy

    render json: {"result" => "success"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.erb
<%= form_for(@coin) do |f| %>
  <% if @coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% @coin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :num_coins %><br />
    <%= f.number_field :num_coins %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render 'form' %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<h1>Listing coins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Num coins</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coins.each do |coin| %>
  <tr>
    <td><%= coin.name %></td>
    <td><%= coin.num_coins %></td>
    <td><%= link_to 'Show', coin %></td>
    <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
    <td><%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render 'form' %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @coin.name %>
</p>

<p>
  <b>Num coins:</b>
  <%= @coin.num_coins %>
</p>


<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/home/index.html.erb
<div id="main-container">
  <div id="header-container">
    <img src="/assets/WON.png" />&nbsp;Wuthless Coins
  </div>
  <div id="content-container">
  <% @coins.each do |coin| %>
    <div class="wuthless-name"><%= coin.name %></div>
    <div class="wuthless-coins"><%= coin.num_coins %></div>
    <div class="clear"></div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wuthlesscoin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>